# Default values for blue-green-app
replicaCount: 2

image:
  repository: gajjarvatsall/blue-green-demo-app  # Change this
  pullPolicy: IfNotPresent
  tag: "1.0.0"

registry:
  dockerhub:
    enabled: true
    username: gajjarvatsall
    repository: blue-green-demo-app

# Blue-Green Configuration
blueGreen:
  enabled: true
  activeEnvironment: "blue"  # blue or green
  
environment:
  name: "blue"  # Will be overridden during deployment
  
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: blue-green-demo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

database:
  host: "localhost"
  port: 5432
  name: "ecommerce"

monitoring:
  enabled: true


healthChecker:
  image:
    repository: blue-green-health-checker
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"



resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health check configuration
healthcheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /ready
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  enabled: true
  path: /live
  initialDelaySeconds: 15
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3