name: Blue-Green Deployment Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: true
        default: "latest"
      environment:
        description: "Target environment (blue/green)"
        required: false
        default: "auto"
      auto_switch:
        description: "Auto switch traffic after health checks"
        required: false
        default: false
        type: boolean

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/blue-green-demo-app
  CLUSTER_NAME: blue-green-cluster

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event.inputs.version != '' }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Debug build outputs
        run: |
          echo "🐛 Debug Information:"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Image digest: ${{ steps.build.outputs.digest }}"

  determine-environment:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      target-env: ${{ steps.determine.outputs.target-env }}
      current-active: ${{ steps.determine.outputs.current-active }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up KIND cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: kind-config.yaml

      - name: Determine target environment
        id: determine
        run: |
          # Get current active environment
          ACTIVE=$(kubectl get configmap blue-green-config -o jsonpath='{.data.active-environment}' 2>/dev/null || echo "blue")

          if [ "${{ github.event.inputs.environment }}" = "auto" ] || [ -z "${{ github.event.inputs.environment }}" ]; then
            if [ "$ACTIVE" = "blue" ]; then
              TARGET="green"
            else
              TARGET="blue"
            fi
          else
            TARGET="${{ github.event.inputs.environment }}"
          fi

          echo "current-active=$ACTIVE" >> $GITHUB_OUTPUT
          echo "target-env=$TARGET" >> $GITHUB_OUTPUT
          echo "🎯 Current active: $ACTIVE, Target: $TARGET"

  deploy:
    runs-on: ubuntu-latest
    needs: [build, determine-environment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up KIND cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: kind-config.yaml

      - name: Install NGINX Ingress
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s

      - name: Load Docker image to KIND
        run: |
          # Extract image tag from build output
          IMAGE_TAG=$(echo '${{ needs.build.outputs.image-tag }}' | head -n1)
          echo "Raw image tags: ${{ needs.build.outputs.image-tag }}"
          echo "Selected image tag: $IMAGE_TAG"

          # Validate that IMAGE_TAG is not empty
          if [ -z "$IMAGE_TAG" ]; then
            echo "❌ Error: IMAGE_TAG is empty"
            echo "Available tags: ${{ needs.build.outputs.image-tag }}"
            exit 1
          fi

          # Pull the image from Docker Hub
          echo "Pulling image: $IMAGE_TAG"
          docker pull $IMAGE_TAG

          # Load image into KIND cluster
          echo "Loading image into KIND cluster..."
          kind load docker-image $IMAGE_TAG --name ${{ env.CLUSTER_NAME }}

      - name: Deploy to target environment
        env:
          TARGET_ENV: ${{ needs.determine-environment.outputs.target-env }}
        run: |
          IMAGE_TAG=$(echo '${{ needs.build.outputs.image-tag }}' | head -n1)

          # Validate IMAGE_TAG
          if [ -z "$IMAGE_TAG" ]; then
            echo "❌ Error: IMAGE_TAG is empty"
            echo "Available tags: ${{ needs.build.outputs.image-tag }}"
            exit 1
          fi

          VERSION=$(echo $IMAGE_TAG | cut -d: -f2)
          IMAGE_REPO=$(echo $IMAGE_TAG | cut -d: -f1)

          echo "🚀 Deploying to $TARGET_ENV environment"
          echo "📦 Image: $IMAGE_TAG"
          echo "🏷️  Version: $VERSION"
          echo "📍 Repository: $IMAGE_REPO"

          helm upgrade --install blue-green-demo-$TARGET_ENV ./blue-green-app \
            --set environment.name=$TARGET_ENV \
            --set image.tag=$VERSION \
            --set image.repository=$IMAGE_REPO \
            --wait --timeout=5m

      - name: Wait for deployment
        run: |
          TARGET_ENV=${{ needs.determine-environment.outputs.target-env }}
          DEPLOYMENT_NAME="blue-green-demo-$TARGET_ENV-blue-green-app"
          echo "Waiting for deployment: $DEPLOYMENT_NAME"
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s

  health-check:
    runs-on: ubuntu-latest
    needs: [deploy, determine-environment]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up KIND cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: kind-config.yaml

      - name: Run comprehensive health checks
        run: |
          chmod +x ./scripts/health-check.sh
          ./scripts/health-check.sh ${{ needs.determine-environment.outputs.target-env }}

      - name: Performance test
        run: |
          TARGET_ENV=${{ needs.determine-environment.outputs.target-env }}
          SERVICE_NAME="blue-green-demo-$TARGET_ENV-blue-green-app"

          # Port forward for testing
          kubectl port-forward service/$SERVICE_NAME 8080:3000 &
          PF_PID=$!
          sleep 5

          # Run basic performance test
          for i in {1..10}; do
            echo "Performance test $i/10"
            curl -f http://localhost:8080/health || exit 1
            curl -f http://localhost:8080/ || exit 1
          done

          kill $PF_PID
          echo "✅ Performance tests completed"

  traffic-switch:
    runs-on: ubuntu-latest
    needs: [health-check, determine-environment]
    if: ${{ github.event.inputs.auto_switch == 'true' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up KIND cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          config: kind-config.yaml

      - name: Switch traffic
        run: |
          chmod +x ./scripts/traffic-switch.sh
          ./scripts/traffic-switch.sh ${{ needs.determine-environment.outputs.target-env }}

      - name: Verify traffic switch
        run: |
          sleep 10
          # Test the main ingress endpoint
          kubectl port-forward service/ingress-nginx-controller -n ingress-nginx 8080:80 &
          PF_PID=$!
          sleep 5

          for i in {1..10}; do
            RESPONSE=$(curl -s http://localhost:8080/api/version)
            echo "Response $i: $RESPONSE"
          done

          kill $PF_PID

  notify:
    runs-on: ubuntu-latest
    needs: [traffic-switch, determine-environment]
    if: always()
    steps:
      - name: Deployment notification
        run: |
          if [ "${{ needs.traffic-switch.result }}" = "success" ]; then
            echo "✅ Blue-Green deployment successful!"
            echo "🎯 Traffic switched to: ${{ needs.determine-environment.outputs.target-env }}"
          else
            echo "❌ Deployment failed or traffic switch was skipped"
          fi
