name: Emergency Rollback

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Rollback reason'
        required: true
        default: 'Emergency rollback'

env:
  CLUSTER_NAME: blue-green-cluster

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up KIND cluster
      uses: helm/kind-action@v1.4.0
      with:
        cluster_name: ${{ env.CLUSTER_NAME }}
        config: kind-config.yaml

    - name: Emergency rollback
      run: |
        chmod +x ./scripts/rollback.sh
        ./scripts/rollback.sh "${{ github.event.inputs.reason }}"

    - name: Verify rollback
      run: |
        echo "🔄 Rollback initiated: ${{ github.event.inputs.reason }}"
        kubectl get configmap blue-green-config -o yaml